
const thumbProductsFile = "/productsThumbs";
const bannerProductsFile = "/productsBanners";

export const products = [
  {
    id: "consorcio-de-imoveis",
    image: thumbProductsFile + "/Consorcio-de-Imoveis.jpg",
    title: "Consórcio de Imóvel",
    text: "Com o consórcio imóvel você pode: comprar casa ou apartamento, construir, reformar ou comprar um terreno com parcelas acessíveis e sem juros.",
    url: "/consórcio-imóvel",
  },
  {
    id: "seguro-notebook",
    image: thumbProductsFile + "/Seguro-Notebook.jpg",
    title: "Seguro para Notebook",
    text: "O seguro proporciona a reposição do seu equipamento em casos de danos ou roubo.",
    url: "/seguro-para-notebook",
  },
  {
    id: "seguro-auto-senior",
    image: thumbProductsFile + "/Seguro-Auto-Senior.jpg",
    title: "Seguro Auto Sênior",
    text: "São diversas vantagens para quem tem a partir de 60 anos!",
    url: "/seguro-auto-sênior",
  },
  {
    id: "seguro-acidentes-pessoais-escolar",
    image: thumbProductsFile + "/Seguro-Acidentes-Pessoais-Escolar.jpg",
    title: "Seguro de Acidentes Pessoais Escolar",
    text: "Proteção e assistência para alunos. Tranquilidade para pais, responsáveis e estabelecimentos de ensino.",
    url: "/seguro-de-acidentes-pessoais-coletivo-escolar",
  },
  {
    id: "seguro-acidentes-pessoais-plus",
    image: thumbProductsFile + "/Seguro-Acidentes-Pessoais-Plus.jpg",
    title: "Seguro de Acidentes Pessoais Plus",
    text: "Vantagens e benefícios exclusivos para dar mais tranquilidade e segurança para você e sua família em casos de acidentes.",
    url: "/seguro-de-acidentes-pessoais-plus",
  },
  {
    id: "seguro-acidentes-pessoais-individual-prazo-curto",
    image: thumbProductsFile + "/Seguro-Acidentes-Pessoais-Individual-Prazo-Curto.jpg",
    title: "Seguro de Acidentes Pessoais Individual Prazo Curto",
    text: "Para sua tranquilidade, proteção e auxílio completo em casos de acidente.",
    url: "/seguro-de-acidentes-pessoais-individual-curto-prazo",
  },
  {
    id: "seguro-auto-mulher",
    image: thumbProductsFile + "/Seguro-Auto-Mulher.jpg",
    title: "Seguro Auto Mulher",
    text: "Um seguro que além de proteger o seu automóvel e também cuida de você.",
    url: "/seguro-auto-mulher",
  },
  {
    id: "seguro-apartamentos",
    image: thumbProductsFile + "/Seguro-Apartamentos.png",
    title: "Seguro Apartamentos",
    text: "O Seguro Apartamentos foi criado para atender os moradores desse tipo de imóvel, oferecendo coberturas.",
    url: "/seguro-apartamentos",
  },
  {
    id: "consorcio-veiculos",
    image: thumbProductsFile + "/Consorcio-Veiculos.jpg",
    title: "Consórcio de Veículos",
    text: "Adquirir ou trocar seu carro fica bem mais fácil quando você tem o capital para esse investimento.",
    url: "/consórcio-automóvel",
  },
  {
    id: "seguro-auto-pequenas-empresas",
    image: thumbProductsFile + "/Auto-Pequenas-Empresas.jpg",
    title: "Seguro Auto Pequenas Empresas",
    text: "Os veículos da sua empresa protegidos e com benefícios exclusivos.",
    url: "/auto-pequenas-empresas",
  },
  {
    id: "seguro_condominio",
    image: thumbProductsFile + "/Seguro-Condominio.jpg",
    title: "Seguro Condomínio",
    text: "Com Seguro Condomínio você deixa de se preocupar com eventuais problemas e ainda acumula vantagens.",
    url: "/seguro-condomínio",
  },
  {
    id: "consorcio",
    image: thumbProductsFile + "/Consorcio.png",
    title: "Consórcio",
    text: "A realização dos seus sonhos fica mais fácil com um plano de consórcio.",
    url: "/consórcio",
  },
  {
    id: "seguro-residencia-premium",
    image: thumbProductsFile + "/Seguro-Residencia-Premium.jpg",
    title: "Seguro Residência Premium",
    text: "O Seguro Residência Premium oferece coberturas que garantem maior proteção para a sua residência, incluindo garantias para obras de arte, joias e relógios, danos ao jardim, danos causados aos empregados, entre outras.",
    url: "/seguro-residência-premium",
  },
  {
    id: "seguro-vida-mais-mulher",
    image: thumbProductsFile + "/Seguro-Vida-Mais-Mulher.jpg",
    title: "Seguro de Vida Mais Mulher",
    text: "Enquanto você cuida da casa, dos negócios e das pessoas que você mais ama, o Seguro Vida Mais Mulher cuida de você.",
    url: "/seguro-de-vida-mais-mulher",
  },
  {
    id: "seguro-residencial-facil",
    image: thumbProductsFile + "/Seguro-Residencial-Facil.jpg",
    title: "Seguro Residencial Fácil",
    text: "Um seguro descomplicado, que ampara seu lar e seus bens com coberturas indispensáveis.",
    url: "/seguro-residencial-simplificado",
  },
  {
    id: "seguro-camera-fotografica",
    image: thumbProductsFile + "/Seguro-para-Camera-Fotografica.jpg",
    title: "Seguro para Câmera Fotográfica",
    text: "O seguro para proporcionar a reposição do seu equipamento em casos de danos ou roubo.",
    url: "/seguro-para-câmera-fotográficas",
  },
  {
    id: "seguro-residencia-veraneio",
    image: thumbProductsFile + "/Seguro-Residencia-Veraneio.jpg",
    title: "Seguro Residência Veraneio",
    text: "Proteção e serviços para você aproveitar o seu cantinho na praia ou no campo.",
    url: "/seguro-residência-veraneio",
  },
  {
    id: "seguro-tablet",
    image: thumbProductsFile + "/Seguro-Tablet.png",
    title: "Seguro para Tablet",
    text: "O seguro para tablets oferece a reposição do seu aparelho em casos de danos ou roubo. Saiba mais sobre o serviço.",
    url: "/seguro-para-tablet",
  },
  {
    id: "seguro-auto-jovem",
    image: thumbProductsFile + "/Seguro-Auto-Jovem.jpg",
    title: "Seguro Auto Jovem",
    text: "O seguro para você que tem um longo caminho pela frente, além de proteger seu carro, tem vantagens.",
    url: "/seguro-auto-jovem",
  },
  {
    id: "seguro-residencia-habitual",
    image: thumbProductsFile + "/Seguro-Residencia-Habitual.jpg",
    title: "Seguro Residência Habitual",
    text: "O Seguro Residência foi feito para garantir o seu patrimônio e superar suas expectativas.",
    url: "/seguro-residência-habitual",
  },
  {
    id: "seguro-filmadora",
    image: thumbProductsFile + "/Seguro-Filmadora.jpg",
    title: "Seguro para Filmadora",
    text: "O seguro para filmadora garante a reposição do seu equipamento em casos de danos ou roubo.",
    url: "/seguro-para-filmadora",
  },
  {
    id: "seguro-vida-pequenas-medias-empresas",
    image: thumbProductsFile + "/Seguro-Vida-Pequenas-Medias-Empresas.jpg",
    title: "Seguro de Vida Pequenas e Médias Empresas",
    text: "O Seguro de Vida Pequenas e Médias Empresas oferece proteção, diversas vantagens e benefícios.",
    url: "/seguro-de-vida-pequenas-e-médias-empresas",
  },
  {
    id: "seguro-celular",
    image: thumbProductsFile + "/Seguro-Celular.jpg",
    title: "Seguro para Celular",
    text: "O serviço dá a tranquilidade necessária em casos de danos físicos no aparelho ou de roubos.",
    url: "/seguro-para-smartphone",
  },
  {
    id: "seguro-vida-grupo",
    image: thumbProductsFile + "/Seguro-Vida-Grupo.jpg",
    title: "Seguro de Vida em Grupo",
    text: "Você pensa no futuro dos seus colaboradores e eles investem no presente da sua empresa.",
    url: "/seguro-de-vida-em-grupo",
  },
  {
    id: "seguro-caminhao",
    image: thumbProductsFile + "/Seguro-Caminhao.jpg",
    title: "Seguro Caminhão",
    text: "O Seguro Caminhão garante coberturas e serviços que atendem a sua necessidade.",
    url: "/seguro-caminhão",
  },

  {
    id: "seguro-taxi",
    image: thumbProductsFile +  "/Seguro-Taxi.jpg",
    title: "Seguro Táxi",
    text: "O seguro que oferece serviços gratuitos, assistência rápida e descontos especiais para taxistas.",
    url: "/porto-seguro-táxi",
  },
  {
    id: "seguro-convencoes-coletivas",
    image: thumbProductsFile + "/Seguro-Convencoes-Coletivas.jpg",
    title: "Seguro para Convenções Coletivas",
    text: "Uma empresa de sucesso se preocupa com o bem-estar e com o futuro de seus colaboradores.",
    url: "/seguro-de-convenções-coletivas",
  },
  {
    id: "seguro-auto-premium",
    image: thumbProductsFile + "/Seguro-Auto-Premium.jpg",
    title: "Seguro Auto Premium",
    text: "Exclusivo, como você. Rede de oficinas premium, assistência 24h, concierge, entre outros diferenciais.",
    url: "/auto-premium",
  },
  {
    id: "seguro-vida-individual",
    image: thumbProductsFile + "/Seguro-Vida-Individual.jpg",
    title: "Seguro de Vida Individual",
    text: "O Seguro Vida Individual garante a sua tranquilidade e a de sua família, agora e no futuro.",
    url: "/seguro-de-vida-individual",
  },
  {
    id: "alarmes-monitoramento",
    image: thumbProductsFile + "/Alarmes-Monitoramento.jpg",
    title: "Alarmes e Monitoramento",
    text: "Proteção, rastreamento e monitoramento para seus bens imóveis e para suas cargas.",
    url: "/proteção-e-monitoramento",
  },
];