import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { Page } from "components/Page";
import { Content } from "components/Content";
import { PageTitle } from "components/PageTitle";
import { PageConstructor } from "components/PageConstructor";

function PoliticaPrivacidade({
  pageTitle,
  description,
  texts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { asPath } = useRouter();

  return (
    <React.Fragment>
      <Head>
        <title>MPR - Seguros Auto, Vida e Viagem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description={description}>
        <Content>
          <PageTitle pageTitle={pageTitle} pageUrl={asPath} />
          <PageConstructor text={texts} />
        </Content>
      </Page>
    </React.Fragment>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Política de privacidade";
  const description = "Saiba mais sobre nossa política de privacidade.";
  const texts = [
    {
      id: "paragraph_01",
      type: "paragraph",
      text: "Em tudo que fazemos, buscamos proteger nossos dados e informações. Seus dados pessoais são bens valiosos que devem ser preservados. Por isso você precisa saber exatamente como eles podem ser utilizados. Foi justamente para isso que criamos essa Política de Privacidade.",
    },
    {
      id: "paragraphN_01",
      type: "paragraphN",
      text: "Como coletamos dados pessoais sobre você?",
    },

    {
      id: "paragraph_02",
      type: "paragraph",
      text: "Coletamos as informações que você compartilha, mediante consentimento, ao solicitar informações/cotações de nossos produtos e serviços, através do preenchimento dos formulários que disponibilizamos em nosso site.",
    },
    {
      id: "paragraphN_02",
      type: "paragraphN",
      text: "Como usamos os seus dados?",
    },
    {
      id: "paragraph_03",
      type: "paragraph",
      text: "Utilizamos seus dados, com o seu consentimento, para:",
    },

    {
      id: "list_01",
      type: "iconlist",
      texts: [
        {
          id: "listItem_01",
          type: "listItem",
          text: "informar oferta de produtos/serviços ou campanhas promocionais;",
        },
        {
          id: "listItem_02",
          type: "listItem",
          text: "entrar em contato para realizar atendimento;",
        },
        {
          id: "listItem_03",
          type: "listItem",
          text: "esclarecer suas dúvidas sobre nossos produtos;",
        },
        {
          id: "listItem_04",
          type: "listItem",
          text: "calcular e enviar as cotações solicitadas.",
        },
      ],
    },
    {
      id: "paragraphN_03",
      type: "paragraphN",
      text: "Com quem compartilhamos os seus dados?",
    },
    {
      id: "paragraph_04",
      type: "paragraph",
      text: "Os seus dados não são compartilhados com terceiros.",
    },
    {
      id: "paragraphN_04",
      type: "paragraphN",
      text: "Como protegemos os seus dados?",
    },
    {
      id: "paragraph_05",
      type: "paragraph",
      text: "Adotamos práticas e tecnologias alinhadas aos padrões técnicos e regulatórios de mercado, bem como controles que são sempre revisados e aprimorados. Seus dados pessoais são armazenados em local seguro, por meio da tecnologia cloud.",
    },
    {
      id: "paragraphN_05",
      type: "paragraphN",
      text: "Quais são os seus direitos em relação aos dados?",
    },
    {
      id: "paragraph_06",
      type: "paragraph",
      text: "A qualquer momento, através dos meios de contato disponibilizados em nosso site, você poderá:",
    },

    {
      id: "list_02",
      type: "iconlist",
      texts: [
        {
          id: "listItem_01",
          type: "listItem",
          text: "solicitar informações quais dados pessoais foram armazenados;",
        },
        {
          id: "listItem_02",
          type: "listItem",
          text: "solicitar a retificação ou atualização dos seus dados pessoais;",
        },
        {
          id: "listItem_03",
          type: "listItem",
          text: "solicitar a eliminação dos seus dados de nossa base de dados, desde que não exista algum impedimento legal ou regulatório que nos obrigue a mantê-los;",
        },
        {
          id: "listItem_04",
          type: "listItem",
          text: "solicitar o não recebimento de e-mails marketing, enviados automaticamente pelo nosso site;",
        },
        {
          id: "listItem_05",
          type: "listItem",
          text: "solicitar o seu cadastro para receber e-mails contendo oferta de produtos/serviços ou campanhas promocionais.",
        },
      ],
    },

    {
      id: "paragraphN_06",
      type: "paragraphN",
      text: "Cookies",
    },
    {
      id: "paragraph_07",
      type: "paragraph",
      text: "Cookies são arquivos temporários que armazenam informações, mediante consentimento, para melhorar a sua experiência em nosso site. Periodicamente solicitaremos a sua autorização para armazenar esses arquivos.",
    },

    {
      id: "paragraphN_07",
      type: "paragraphN",
      text: "Contato",
    },
    {
      id: "paragraph_08",
      type: "paragraph",
      text: "Caso precise de qualquer suporte ou tenha alguma dúvida, pedido ou sugestão em relação a essa Política, por favor entre em contato através de algum dos canais de atendimento divulgados em nosso site.",
    },
  ];

  return {
    props: {
      pageTitle,
      description,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default PoliticaPrivacidade;
