import Head from "next/head";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { Page } from "components/Page";
import { Content } from "components/Content";

function Produtos({
  pageTitle,
  description,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>MPR - Seguros Auto, Vida e Viagem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description={description}>
        <Content></Content>
      </Page>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Produtos";
  const description = "Produtos";
  const texts = "";

  return {
    props: {
      pageTitle,
      description,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default Produtos;
