import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { Page } from "components/Page";
import { Content } from "components/Content";
import { PageTitle } from "components/PageTitle";
import { PageConstructor } from "components/PageConstructor";

function QuemSomos({
  pageTitle,
  description,
  texts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { asPath } = useRouter();

  return (
    <React.Fragment>
      <Head>
        <title>MPR - Seguros Auto, Vida e Viagem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description={description}>
        <Content>
          <PageTitle pageTitle={pageTitle} pageUrl={asPath} />
          <PageConstructor text={texts} />
        </Content>
      </Page>
    </React.Fragment>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Sobre a corretora";
  const description = "Saiba mais sobre a MPR.";
  const texts = [
    {
      id: "paragraphN_01",
      type: "paragraphN",
      text: "A Empresa:",
    },
    {
      id: "paragraph_01",
      type: "paragraph",
      text: "A MPR é uma empresa 100% nacional, que iniciou seus trabalhos no ano de 2003, é uma empresa especializada em consultoria de seguros, formada por profissionais com alto grau de especialização e competência, que investem em manter e consolidar um modelo diferenciado de gestão, pré requisito para que a empresa se posicione entre as principais de seu ramo de atividade.",
    },
    {
      id: "paragraph_02",
      type: "paragraph",
      text: "Hoje podemos afirmar que o nosso diferencial é o foco nos resultados, e na satisfação; temos uma experiência na identificação da necessidade, podendo assim customizar o produto que oferecemos ao nosso cliente. ",
    },
    {
      id: "paragraphN_02",
      type: "paragraphN",
      text: "Missão coorporativa:",
    },
    {
      id: "paragraph_03",
      type: "paragraph",
      text: "Prestar os melhores serviços em consultoria de seguros, ou seja, transformar conhecimentos e sonhos em realidade visando o bom atendimento, e comercializar sempre os melhores produtos, para promover o bem estar de nossos clientes.",
    },
    {
      id: "paragraphN_03",
      type: "paragraphN",
      text: "Visão:",
    },
    {
      id: "paragraph_04",
      type: "paragraph",
      text: "Ser reconhecida como uma das grandes empresas corretoras de seguros no Brasil, buscando excelência em tudo que fizermos, crescendo continuamente com caráter empreendedor, talento de seus profissionais, gerando valores, e priorizando segurança e tranqüilidade.",
    },
    {
      id: "paragraphN_04",
      type: "paragraphN",
      text: "Valores:",
    },
    {
      id: "paragraph_05",
      type: "paragraph",
      text: "Ética, excelência pessoal e profissional, inovação, competitividade, comprometimento, trabalho em equipe, tudo isto focando nosso principal patrimônio, nossos clientes.",
    },
  ];

  return {
    props: {
      pageTitle,
      description,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default QuemSomos;
