import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { Page } from "components/Page";
import { Content } from "components/Content";
import { PageTitle } from "components/PageTitle";
import { PageConstructor } from "components/PageConstructor";

function TelefonesUteis({
  pageTitle,
  description,
  texts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { asPath } = useRouter();

  return (
    <React.Fragment>
      <Head>
        <title>MPR - Seguros Auto, Vida e Viagem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Page title={pageTitle} description={description}>
        <Content>
          <PageTitle pageTitle={pageTitle} pageUrl={asPath} />
          <PageConstructor text={texts} />
        </Content>
      </Page>
    </React.Fragment>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Telefones úteis";
  const description = "Telefones úteis quando precisar de atendimento.";
  const texts = [
    {
      id: "accordion_01",
      type: "accordion",
      texts: [
        {
          id: "accordionItem_01",
          type: "accordionItem",
          text: "PORTO CONSÓRCIO",
          content: [
            {
              id: "iconlist_01",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2743 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_01",
              type: "paragraphN",
              text: "Central de Relacionamento:",
            },
            {
              id: "iconlist_02",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-3006 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 721 3006 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_02",
          type: "accordionItem",
          text: "PORTO SEGURO ALUGUEL",
          content: [
            {
              id: "iconlist_03",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2748 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_02",
              type: "paragraphN",
              text: "Solicitação de serviços / sinistro:",
            },
            {
              id: "iconlist_04",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "ALUGUEL o mesmo que 3258-4835 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 727 0901 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_03",
          type: "accordionItem",
          text: "AZUL SEGUROS",
          content: [
            {
              id: "iconlist_05",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 703 1280 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_03",
              type: "paragraphN",
              text: "Solicitação de serviços / sinistro / benefícios:",
            },
            {
              id: "iconlist_06",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "4004-3700 (capitais e grandes centros)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 703 0203 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_04",
          type: "accordionItem",
          text: "PORTO SEGURO TRANSPORTES",
          content: [
            {
              id: "iconlist_07",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2761 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_04",
              type: "paragraphN",
              text: "Solicitação de serviços / sinistro:",
            },
            {
              id: "iconlist_08",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-8080 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 727 2755 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_05",
          type: "accordionItem",
          text: "CARTÃO PORTO SEGURO VISA",
          content: [
            {
              id: "iconlist_09",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2769 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_05",
              type: "paragraphN",
              text: "Central de Relacionamento:",
            },
            {
              id: "iconlist_10",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "4004-3600 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 727 7477 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_06",
          type: "accordionItem",
          text: "PORTOSEG - CRÉDITO E FINANCIAMENTO",
          content: [
            {
              id: "iconlist_11",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2745 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_06",
              type: "paragraphN",
              text: "Solicitação de serviços:",
            },
            {
              id: "iconlist_12",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-6066 (Grande São Paulo)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_07",
          type: "accordionItem",
          text: "PORTO SEGURO VIDA E PREVIDÊNCIA",
          content: [
            {
              id: "iconlist_13",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2746 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_07",
              type: "paragraphN",
              text: "Atendimento Vida e Previdência",
            },
            {
              id: "iconlist_14",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-3377 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800-727 9393 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_08",
          type: "accordionItem",
          text: "PORTO SEGURO AUTO - Automóvel e Moto",
          content: [
            {
              id: "iconlist_15",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2766 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_08",
              type: "paragraphN",
              text: "Solicitação de serviços / sinistro:",
            },
            {
              id: "iconlist_16",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "333-PORTO o mesmo que 333-76786 (Grande São Paulo e Grande Rio)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "4004-PORTO o mesmo que 4004-76786 (Capitais e Grandes Centros)",
                },
                {
                  id: "listItem_03",
                  type: "listItem",
                  text: "0800 727 0800 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_09",
          type: "accordionItem",
          text: "PORTO SEGURO - Ramos Elementares",
          content: [
            {
              id: "paragraph_01",
              type: "paragraph",
              text: "Seguro Residência, Residência Simplificado, Imobiliárias, Condomínio, Empresa, Multirisco, Bares & Restaurantes, Hotéis & Pousadas, Riscos de Engenharia, Equipamentos Portáteis, Agrícola e Concessionárias.",
            },
            {
              id: "iconlist_17",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2765 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_09",
              type: "paragraphN",
              text: "Solicitação de serviços / sinistro:",
            },
            {
              id: "iconlist_18",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-3110 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 727 8118 (Demais Localidades)",
                },
              ],
            },
          ],
        },
        {
          id: "accordionItem_10",
          type: "accordionItem",
          text: "PORTO SEGURO SAÚDE E ODONTOLÓGICO",
          content: [
            {
              id: "iconlist_19",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "SAC: 0800 727 2762 (informações, reclamações e cancelamentos)",
                },
              ],
            },
            {
              id: "paragraphN_10",
              type: "paragraphN",
              text: "Solicitação de serviços / senhas:",
            },
            {
              id: "iconlist_20",
              type: "iconlist",
              texts: [
                {
                  id: "listItem_01",
                  type: "listItem",
                  text: "3366-3003 (Grande São Paulo)",
                },
                {
                  id: "listItem_02",
                  type: "listItem",
                  text: "0800 727 2800 (Demais Localidades)",
                },
              ],
            },
          ],
        },
      ],
    },
  ];

  return {
    props: {
      pageTitle,
      description,
      texts,
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
};

export default TelefonesUteis;
